<a href="https://colab.research.google.com/github/alokchoudharyguliya/Tensorflow-Practice/blob/main/Basics_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tensor_zero_d=tf.constant(3)

In [ ]:
import numpy as np
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))


tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tensor_zero_d=tf.constant(4)


In [ ]:
eye_tensor=tf.eye(
    num_rows=5,num_columns=None,batch_shape=[2,4],dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# x_3.T = 4,2
# x_2.T = 2,3
print(tf.transpose(x_3)@tf.transpose(x_2))
tf.linalg.matmul(
    x_3, x_2, transpose_a=True, transpose_b=False, adjoint_a=False, adjoint_b=True,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]], dtype=int32)>

In [ ]:
x_1@x_2

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 12]], dtype=int32)>